# Generated by Django 2.0.1 on 2018-02-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_fruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='fruit',
        ),
    ]
