# Generated by Django 2.0.1 on 2018-02-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
        ('characters', '0003_remove_character_fruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fruit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fruits.DevilFruit'),
            preserve_default=False,
        ),
    ]
