# Generated by Django 2.0.1 on 2018-02-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('total_bounty', models.IntegerField(default=0)),
                ('count_members', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ManyToManyField(to='characters.Character')),
            ],
            options={
                'verbose_name': 'Affilation',
                'verbose_name_plural': 'Affilation',
                'ordering': ['-timestamp'],
            },
        ),
    ]
