# Generated by Django 2.0.1 on 2018-02-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20180214_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affilations',
            old_name='member',
            new_name='characters',
        ),
    ]
